// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyZ6muEIkcTjfsvzuNZSGy-4b47ua9Ghw',
    appId: '1:151004501212:web:21d103f9480b4fc1705019',
    messagingSenderId: '151004501212',
    projectId: 'my-notes-app-by-abhay',
    authDomain: 'my-notes-app-by-abhay.firebaseapp.com',
    storageBucket: 'my-notes-app-by-abhay.appspot.com',
    measurementId: 'G-M2H6PT1PX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOt8x5toA98-s0qgsHAe4Z79HSFfCGfM',
    appId: '1:151004501212:android:f2f205f3be757a6e705019',
    messagingSenderId: '151004501212',
    projectId: 'my-notes-app-by-abhay',
    storageBucket: 'my-notes-app-by-abhay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxHiyk258SsU2gdKAsJbb7_h8A7vqiHu0',
    appId: '1:151004501212:ios:718c016133b0a2b7705019',
    messagingSenderId: '151004501212',
    projectId: 'my-notes-app-by-abhay',
    storageBucket: 'my-notes-app-by-abhay.appspot.com',
    iosClientId: '151004501212-fudjpgd37ip78vj8n2eqgv9bc6u8tjgb.apps.googleusercontent.com',
    iosBundleId: 'com.hello.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxHiyk258SsU2gdKAsJbb7_h8A7vqiHu0',
    appId: '1:151004501212:ios:37674c13166e39f3705019',
    messagingSenderId: '151004501212',
    projectId: 'my-notes-app-by-abhay',
    storageBucket: 'my-notes-app-by-abhay.appspot.com',
    iosClientId: '151004501212-ub6jouin1ri8p7eehqldi92j6kpqb7gd.apps.googleusercontent.com',
    iosBundleId: 'com.hello.mynotes.RunnerTests',
  );
}
